module.exports = {
  JWT_SECRET: process.env.JWT_SECRET,
  JWT_EXPIRE: process.env.JWT_EXPIRE,
  
  ROLES: {
    SUPER_ADMIN: 'SUPER_ADMIN',
    TENANT_ADMIN: 'TENANT_ADMIN',
    COLLECTOR: 'COLLECTOR',
    ACCOUNTANT: 'ACCOUNTANT'
  },
  
  PERMISSIONS: {
    // Tenant & Plan
    CREATE_TENANT: 'CREATE_TENANT',
    VIEW_TENANT: 'VIEW_TENANT',
    UPDATE_TENANT: 'UPDATE_TENANT',
    DELETE_TENANT: 'DELETE_TENANT',
    MANAGE_PLAN: 'MANAGE_PLAN',
    
    // User Management
    CREATE_USER: 'CREATE_USER',
    VIEW_USER: 'VIEW_USER',
    UPDATE_USER: 'UPDATE_USER',
    DELETE_USER: 'DELETE_USER',
    MANAGE_ROLE: 'MANAGE_ROLE',
    
    // Market Management
    CREATE_MARKET: 'CREATE_MARKET',
    VIEW_MARKET: 'VIEW_MARKET',
    UPDATE_MARKET: 'UPDATE_MARKET',
    DELETE_MARKET: 'DELETE_MARKET',
    CREATE_ZONE: 'CREATE_ZONE',
    VIEW_ZONE: 'VIEW_ZONE',
    UPDATE_ZONE: 'UPDATE_ZONE',
    DELETE_ZONE: 'DELETE_ZONE',
    CREATE_KIOSK: 'CREATE_KIOSK',
    VIEW_KIOSK: 'VIEW_KIOSK',
    UPDATE_KIOSK: 'UPDATE_KIOSK',
    DELETE_KIOSK: 'DELETE_KIOSK',
    
    // Merchant Management
    CREATE_MERCHANT: 'CREATE_MERCHANT',
    VIEW_MERCHANT: 'VIEW_MERCHANT',
    UPDATE_MERCHANT: 'UPDATE_MERCHANT',
    DELETE_MERCHANT: 'DELETE_MERCHANT',
    ASSIGN_KIOSK: 'ASSIGN_KIOSK',
    
    // Fee Management
    CREATE_FEE: 'CREATE_FEE',
    VIEW_FEE: 'VIEW_FEE',
    UPDATE_FEE: 'UPDATE_FEE',
    DELETE_FEE: 'DELETE_FEE',
    APPLY_FEE: 'APPLY_FEE',
    
    // Collection
    CREATE_PERIOD: 'CREATE_PERIOD',
    VIEW_PERIOD: 'VIEW_PERIOD',
    GENERATE_CHARGE: 'GENERATE_CHARGE',
    VIEW_CHARGE: 'VIEW_CHARGE',
    COLLECT_FEE: 'COLLECT_FEE',
    VIEW_RECEIPT: 'VIEW_RECEIPT',
    
    // Shift Management
    START_SHIFT: 'START_SHIFT',
    END_SHIFT: 'END_SHIFT',
    VIEW_SHIFT: 'VIEW_SHIFT',
    
    // Debt Management
    VIEW_DEBT: 'VIEW_DEBT',
    UPDATE_DEBT_STATUS: 'UPDATE_DEBT_STATUS',
    
    // Reports
    VIEW_REPORT: 'VIEW_REPORT',
    EXPORT_REPORT: 'EXPORT_REPORT',
    
    // System
    VIEW_AUDIT_LOG: 'VIEW_AUDIT_LOG',
    CREATE_NOTIFICATION: 'CREATE_NOTIFICATION',
    VIEW_NOTIFICATION: 'VIEW_NOTIFICATION'
  }
};