const ROLES = {
  SUPER_ADMIN: "SUPER_ADMIN",
  TENANT_ADMIN: "TENANT_ADMIN",
  COLLECTOR: "COLLECTOR",
  MERCHANT: "MERCHANT",
};

const ROLE_CREATE_PERMISSION = {
  [ROLES.SUPER_ADMIN]: [ROLES.SUPER_ADMIN, ROLES.TENANT_ADMIN],
  [ROLES.TENANT_ADMIN]: [ROLES.COLLECTOR, ROLES.MERCHANT],
};

module.exports = {
  ROLES,
  ROLE_CREATE_PERMISSION,
};